[tool.poetry]
name = "nth"
version = "0.1.1"
description = ""
authors = ["Nils Olsson <nilso@enosis.net>"]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = {version = "^0.20.0", optional = true}

[tool.poetry.extras]
cli = ["python-dotenv"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pylama = {git = "git@github.com:nilsso/pylama.git"}
black = "^22.6.0"
isort = "^5.10.1"
pyflakes = "2.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportImplicitStringConcatenation = true
reportCallInDefaultInitializer = true
reportUnnecessaryCast = true

[tool.black]
line-length = 90

[tool.isort]
profile = "black"
multi_line_output = 3  # 3/5: less/more compact
line_length = 90
